version: '3'
services:
  management_db:
    # Required to use 9.6 version as it is the same version been used on debian
    # at Redis:2.5 image
    image: postgres:9.6-alpine
    # Save the docker postgres data onto our local machine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tariff_management_development

  management_redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'

  management_sidekiq:
    depends_on:
      - management_db
      - management_redis
    build: .
    # Uncomment below if you want to run sidekick locally
    # command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    links:
      - management_redis

  management:
    build: .
    command: bash -c "bundle exec rake assets:precompile; rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - management_db
      - management_redis
      - management_sidekiq
    env_file:
      - '.env'
    links:
      - management_redis
