:verbose: false
:concurrency:  1
:queues:
  - [rollbacks, 2]
  - [sync, 2]
  - [xml_generation, 3]
  - [default, 5]
:schedule:
  #
  # Syntax:
  #
  # mm hh dd mt wd  command
  #
  # mm minute 0-59
  # hh hour 0-23
  # dd day of month 1-31
  # mt month 1-12
  # wd day of week 0-7 (Sunday = 0 or 7)
  #
  # Online converter: https://crontab.guru/#0_22_*_*_*
  #
  #  UpdatesSynchronizerWorker:
  #    cron: "0 22 * * *" #
  #    description: "UpdatesSynchronizerWorker will run at 10 PM every day"

  SetupPublishedStatusForImportedRecordsWorker:
    cron: "0 1 * * *"
    description: "SetupPublishedStatusForImportedRecordsWorker will run at 1 AM every day"

  RefreshCacheWorker:
    cron: "0 5 * * *"
    description: "RefreshCacheWorker will run at 5 AM every day"

  SearchableDataReindexWorker:
    cron: "5 0 * * *"
    description: "SearchableDataReindexWorker will run at 00:05 every day"

  DownloadXmlWorker:
    cron: '0 * * * * *'
    description: "Polls S3 for responses"
